parameters:
    kafka.bootstrap_servers: '%env(KAFKA_BOOTSTRAP_SERVERS)%'
    kafka.group_id: 'choven_consumer'
    kafka.auto_offset_reset: 'earliest'
    kafka.order_topic: 'orders'
    kafka.email_topic: 'emails'