framework:
    translator:
        logging: true
        pseudo_localization:
            enabled: true
            accents: false
            expansion_factor: 1
            brackets: false
            parse_html: false